site_name: Freifunk Darmstadt
repo_url: https://github.com/freifunk-darmstadt/website-ng
theme:
  name: material
  language: de
  logo: assets/logo/ff-500px.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - search.share
  extra_javascript:
    - javascripts/leaflet.js
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Anleitung für den ersten Freifunk-Knoten: mitmachen/erster-freifunk-knoten.md
  - Kaufberatung: mitmachen/kaufberatung.md
  - Spenden: spenden.md
  - Einzugsgebiet: einzugsgebiet.md
  - Impressum: impressum.md
  - Statistiken: https://stats.darmstadt.freifunk.net
  - Karte: https://meshviewer.darmstadt.freifunk.net
plugins:
  - search
  - privacy
  - redirects:
      redirect_maps:
        'news.md': 'https://chaos.social/@ffda'
        'karte.md': 'https://meshviewer.darmstadt.freifunk.net'
        'mitmachen/unterstuetzte-geraete.md': 'mitmachen/kaufberatung.md'
        'mitmachen.md': 'mitmachen/erster-freifunk-knoten.md'
        'mitmachen/router-einrichten.md': 'mitmachen/erster-freifunk-knoten.md'
        'mitmachen/spenden.md': 'spenden.md'
        'mitmachen/domains.md': 'einzugsgebiet.md'
        'mitmachen/mithelfen.md': 'index.md'
        'was-ist-freifunk.md': 'index.md'
        'was-ist-freifunk/faq.md': 'index.md'
        'chat.md': 'index.md'
        'kontakt.md': 'index.md'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.github.com/freifunk-darmstadt
      name: GitHub Orgainsation
    - icon: fontawesome/brands/gitlab
      link: https://git.darmstadt.ccc.de/ffda
      name: GitLab Orgainsation
    - icon: fontawesome/brands/mastodon
      link: https://chaos.social/@ffda
      name: Mastodon Feed
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true