name: Build Homepage
on: [ push, pull_request]
jobs:
  build-homepage:
    name: build-homepage
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/squidfunk/mkdocs-material:9.5.18
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build with MkDocs
        run: |
          mkdocs build
      - name: Save rendered homepage
        uses: actions/upload-artifact@v4
        with:
          path: site
          name: website
