name: Build Homepage
on: [ push, pull_request]
jobs:
  build-homepage:
    name: build-homepage
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/squidfunk/mkdocs-material:9.5.18
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build with MkDocs
        run: |
          mkdocs build
      - name: Save rendered homepage
        uses: actions/upload-artifact@v4
        with:
          path: site
          name: website

  deploy:
    needs: [ build ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: website
          path: website_data

      - name: Save SSH Key for deployment
        run: >
          mkdir -p ~/.ssh &&
          echo "${{ secrets.GHA_FFDA_WEB_DEPLOY_SSH_KEY }}" >
          ~/.ssh/deploy_key && chmod 600 ~/.ssh/deploy_key

      - name: Deploy website to www3
        run: rsync -avzP -e "ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -oIdentitiesOnly=yes" website_data "ffda_web@www3.darmstadt.freifunk.net:/var/www/darmstadt_freifunk_net"
